DROP TABLE IF EXISTS Title;

CREATE TABLE IF NOT EXISTS Title
(
    ID           INTEGER PRIMARY KEY AUTOINCREMENT,
    Owner        VARCHAR(32) NOT NULL COLLATE NOCASE,
    CurrentTitle TEXT DEFAULT NULL COLLATE NOCASE,
    Titles       TEXT DEFAULT NULL COLLATE NOCASE,
    UNIQUE (Owner)
);

INSERT OR IGNORE INTO Title (Owner)
VALUES (:owner);