package Anarchy;

import Anarchy.Utils.SQLiteUtils;

class SQLProvider {

	public static void register() {
		SQLiteUtils.query("CREATE TABLE IF NOT EXISTS Auth (Username TEXT, VK_ID INTEGER NULL, IP_Reg TEXT NULL, IP_Last TEXT NULL, DATE_REG TEXT NULL, DATE_LAST TEXT NULL);");
		SQLiteUtils.query("CREATE TABLE IF NOT EXISTS Users (Account_ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, Username TEXT, Prefix TEXT NULL, Permission INTEGER DEFAULT 0, Money REAL DEFAULT 0.0, Bonus INTEGER DEFAULT 0, Gametime INTEGER DEFAULT 0);");
		SQLiteUtils.query("CREATE TABLE IF NOT EXISTS Members (Member_ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, Username TEXT, Region_ID INTEGER);");
		SQLiteUtils.query("CREATE TABLE IF NOT EXISTS Areas (Region_ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, DATE_REG TEXT, Username TEXT, Main_X INTEGER, Main_Y INTEGER, Main_Z INTEGER, Pos1_X INTEGER, Pos1_Y INTEGER, Pos1_Z INTEGER, Pos2_X INTEGER, Pos2_Y INTEGER, Pos2_Z INTEGER);");
		SQLiteUtils.query("CREATE TABLE IF NOT EXISTS Homes (Home_ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, Username TEXT, X INTEGER, Y INTEGER, Z INTEGER);");
	}
}