package Anarchy;

import Anarchy.Utils.SQLiteUtils;

class SQLProvider {
	
	static void register() {
		SQLiteUtils.query("Auth.db", "CREATE TABLE IF NOT EXISTS AUTH (Username TEXT PRIMARY KEY, VK_ID INTEGER DEFAULT NULL, IP_Reg TEXT DEFAULT NULL, IP_Last TEXT DEFAULT NULL, DATE_REG TEXT DEFAULT NULL, DATE_LAST TEXT DEFAULT NULL);");
		SQLiteUtils.query("Users.db", "CREATE TABLE  IF NOT EXISTS USERS (Account_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Username TEXT, Prefix TEXT DEFAULT NULL, Permission INTEGER DEFAULT 0, Money INTEGER DEFAULT 0, DonateCase INTEGER DEFAULT 0, Gametime INTEGER DEFAULT 0);");
		SQLiteUtils.query("Regions.db", "CREATE TABLE IF NOT EXISTS MEMBERS (Member_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Username TEXT, Region_ID INTEGER); CREATE TABLE IF NOT EXISTS AREAS (Region_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, DATE_REG TEXT, Username TEXT, Main_X INTEGER, Main_Y INTEGER, Main_Z INTEGER, Pos1_X INTEGER, Pos1_Y INTEGER, Pos1_Z INTEGER, Pos2_X INTEGER, Pos2_Y INTEGER, Pos2_Z INTEGER);");
		SQLiteUtils.query("Homes.db", "CREATE TABLE IF NOT EXISTS HOMES (Home_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Username TEXT, X INTEGER, Y INTEGER, Z INTEGER);");
	}
}