name: AnarchySystem
main: AnarchySystem.Main
version: "${pom.version}"
api: "1.0.11"
load: POSTWORLD
author: Jl1mbo
website: "vk.com/extranons"
depend:
  - MobPlugin
  - ScoreboardAPI
  - Permissions
  - EconomyAPI
  - FakeInventoryAPI
  - FormAPI
  - WorldManager
  - Bosses