package ru.jl1mbo.AnarchyCore;

import ru.jl1mbo.AnarchyCore.Utils.SQLiteUtils;

public class SQLiteProvider {

	public static void register() {
		SQLiteUtils.query("BlockProtection.db", "CREATE TABLE IF NOT EXISTS Members (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, RegionID INTEGER);");
		SQLiteUtils.query("BlockProtection.db",
						  "CREATE TABLE IF NOT EXISTS Areas (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, Main_X INTEGER, Main_Y INTEGER, Main_Z INTEGER, Pos1_X INTEGER, Pos1_Y INTEGER, Pos1_Z INTEGER, Pos2_X INTEGER, Pos2_Y INTEGER, Pos2_Z INTEGER);");
		SQLiteUtils.query("Users.db",
						  "CREATE TABLE IF NOT EXISTS Users (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, XboxID INTEGER, Money REAL DEFAULT 0.0, Permission TEXT DEFAULT player, GameTime INTEGER DEFAULT 0);");
		SQLiteUtils.query("Auth.db",
						  "CREATE TABLE IF NOT EXISTS Auth (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, DateReg TEXT DEFAULT NULL, DateLast TEXT DEFAULT NULL, IpReg TEXT DEFAULT NULL, IpLast TEXT DEFAULT NULL);");
		SQLiteUtils.query("Homes.db", "CREATE TABLE IF NOT EXISTS Homes (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, X INTEGER, Y INTEGER, Z INTEGER);");


		SQLiteUtils.query("Clan.db", "CREATE TABLE IF NOT EXISTS Clans (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ClanName TEXT);");
		SQLiteUtils.query("Clan.db", "CREATE TABLE IF NOT EXISTS Members (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, Role TEXT, ClanID INTEGER);");
		SQLiteUtils.query("Clan.db", "CREATE TABLE IF NOT EXISTS RequestsPlayer (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, ClanID INTEGER);");
		SQLiteUtils.query("Clan.db", "CREATE TABLE IF NOT EXISTS RequestsClan (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, ClanID INTEGER);");

		SQLiteUtils.query("Admins.db", "CREATE TABLE IF NOT EXISTS Bans (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, Reason TEXT, Time DATETIME);");
		SQLiteUtils.query("Admins.db", "CREATE TABLE IF NOT EXISTS IpBans (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Ip TEXT, Reason TEXT, Time DATETIME);");
		SQLiteUtils.query("Admins.db", "CREATE TABLE IF NOT EXISTS Mutes (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, Reason TEXT, Time DATETIME);");

		SQLiteUtils.query("Admins.db",
						  "CREATE TABLE IF NOT EXISTS Spectates (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, Target TEXT, World TEXT, X INTEGER, Y INTEGER, Z INTEGER, namedTag TEXT);");
						  
		SQLiteUtils.query("Storage.db", "CREATE TABLE IF NOT EXISTS Items (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, ItemId INTEGER, ItemDamage INTEGER, ItemCount INTEGER);");
		
		SQLiteUtils.query("Auction.db", "CREATE TABLE IF NOT EXISTS AuctionStorage (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, ItemId INTEGER, ItemDamage INTEGER, ItemCount INTEGER, ItemNBT TEXT);");
	}
}