package ru.jl1mbo.AnarchyCore;

public class SQLiteProvider {

	public static void register() {
		/*SQLiteUtils.query("BlockProtection.db", "CREATE TABLE IF NOT EXISTS Members (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, RegionID INTEGER);");
		SQLiteUtils.query("BlockProtection.db",
						  "CREATE TABLE IF NOT EXISTS Areas (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, Main_X INTEGER, Main_Y INTEGER, Main_Z INTEGER, Pos1_X INTEGER, Pos1_Y INTEGER, Pos1_Z INTEGER, Pos2_X INTEGER, Pos2_Y INTEGER, Pos2_Z INTEGER);");
		SQLiteUtils.query("Clan.db", "CREATE TABLE IF NOT EXISTS Clans (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ClanName TEXT);");
		SQLiteUtils.query("Clan.db", "CREATE TABLE IF NOT EXISTS Members (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, Role TEXT, ClanID INTEGER);");
		SQLiteUtils.query("Clan.db", "CREATE TABLE IF NOT EXISTS RequestsPlayer (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, ClanID INTEGER);");
		SQLiteUtils.query("Clan.db", "CREATE TABLE IF NOT EXISTS RequestsClan (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, ClanID INTEGER);");

		SQLiteUtils.query("Admins.db", "CREATE TABLE IF NOT EXISTS Bans (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, Reason TEXT, Time DATETIME);");
		SQLiteUtils.query("Admins.db", "CREATE TABLE IF NOT EXISTS IpBans (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Ip TEXT, Reason TEXT, Time DATETIME);");
		SQLiteUtils.query("Admins.db", "CREATE TABLE IF NOT EXISTS Mutes (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, Reason TEXT, Time DATETIME);");

		SQLiteUtils.query("Admins.db",
						  "CREATE TABLE IF NOT EXISTS Spectates (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Name TEXT, Target TEXT, World TEXT, X INTEGER, Y INTEGER, Z INTEGER, namedTag TEXT);");*/
	}
}